routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'KontenController@index');

Route::get('baca-artikel/{id}', 'KontenController@baca_artikel');

Route::get('gambar-galeri', 'KontenController@galeri');

Route::get('web-kategori/{id}', 'KontenController@kategori');

Route::get('kontak', 'KontenController@kontak');

Route::post('kontak', [
    'uses' => 'KontenController@simpan_kontak',
    'as' => 'simpan_kontak'
]);

Route::get('login', [
    'uses' => 'KontenController@login',
    'as' => 'login'
]);

Route::post('login', [
    'uses' => 'KontenController@cek_login',
    'as' => 'cek_login'
]);

Route::group(['middleware' => 'auth'], function () {

    Route::get('dashboard', [
        'uses' => 'AdminController@index',
        'as' => 'dashboard'
    ]);

    Route::get('logout', [
        'uses' => 'AdminController@logout',
        'as' => 'logout'
    ]);

    Route::get('baca-kontak/{$id}', [
        'uses' => 'AdminController@baca_kontak',
        'as' => 'baca-kontak'
    ]);

    Route::get('hapus_kontak/{id}', 'AdminController@hapus_kontak');

    Route::resource('artikel', 'ArtikelController');
    Route::resource('kategori', 'KategoriController');
    Route::resource('produk', 'ProdukController');
    Route::resource('galeri', 'GaleriController');
    Route::resource('carousel', 'CarouselController');
    Route::resource('setting', 'SettingController');
    Route::resource('mesin', 'MesinController');

    Route::get('manajemen_gambar_artikel', 'AdminController@manajemen_gambar_artikel');
    Route::post('upload_gambar_artikel', 'AdminController@upload_gambar_artikel');
    Route::get('hapus_gambar_artikel/{file}', 'AdminController@hapus_gambar_artikel');

    Route::get('manajemen_gambar_produk', 'AdminController@manajemen_gambar_produk');
    Route::post('upload_gambar_produk', 'AdminController@upload_gambar_produk');
    Route::get('hapus_gambar_produk/{file}', 'AdminController@hapus_gambar_produk');

    Route::get('manajemen_gambar_galeri', 'AdminController@manajemen_gambar_galeri');
    Route::post('upload_gambar_galeri', 'AdminController@upload_gambar_galeri');
    Route::get('hapus_gambar_galeri/{file}', 'AdminController@hapus_gambar_galeri');

    Route::get('manajemen_gambar_carousel', 'AdminController@manajemen_gambar_carousel');
    Route::post('upload_gambar_carousel', 'AdminController@upload_gambar_carousel');
    Route::get('hapus_gambar_carousel/{file}', 'AdminController@hapus_gambar_carousel');

    Route::get('manajemen_gambar_mesin', 'AdminController@manajemen_gambar_mesin');
    Route::post('upload_gambar_mesin', 'AdminController@upload_gambar_mesin');
    Route::get('hapus_gambar_mesin/{file}', 'AdminController@hapus_gambar_mesin');

});

//Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

//==============================Testing================================//

Route::get('/testing', function () {
    return view('testing');
});

Route::get('/testing2', function () {
    $files = File::allFiles(public_path('images/caraousel'));

    $caraousel = array();

    foreach ($files as $file) {
        array_push($caraousel, basename((string)$file));
    }

    return $caraousel[0];
});

Route::get('/testing3', function () {
    $carousels = App\Carousel::get();
    return $carousels[3]->gambar;
});

Route::get('/caraousel', function () {
    $caraousels = App\Caraousel::all();
    return $caraousels;
});
//=========================== End Testing =================================//

app/kategori.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{

 protected $table = 'kategori';

 public $timestamps = false;

    public function produk(){
    	return $this->hasMany('App\Produk', 'kat_id');
    }
}

app/Http/Controllers/KategoriController.php
<?php

namespace App\Http\Controllers;

use App\Kategori;
use Illuminate\Http\Request;
use Auth;

class KategoriController extends Controller
{
  /**
  * Display a listing of the resource.
  *
  * @return \Illuminate\Http\Response
  */

  public function index()
  {
    $kategori = Kategori::all();
    $subtitle = 'Index';
    $header = 'List Kategori';
    $title ='Data Kategori';
    $user =  Auth::user()->username;

    return view('admins.kategori.index')
    ->with(compact('kategori'))
    ->with(compact('title'))
    ->with(compact('subtitle'))
    ->with(compact('header'))
    ->with(compact('user'));
  }

  /**
  * Show the form for creating a new resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function create()
  {
    $subtitle = 'Input ';
    $header = 'Input Kategori';
    $title = 'Data Kategori';
    $user =  Auth::user()->username;

    return view('admins.kategori.addnew')
    ->with(compact('title'))
    ->with(compact('subtitle'))
    ->with(compact('header'))
    ->with(compact('user'));
  }

  /**
  * Store a newly created resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @return \Illuminate\Http\Response
  */
  public function store(Request $request)
  {

    $kategori = new Kategori;

    $kategori->nama = $request->input('nama');
    $kategori->keterangan = $request->input('keterangan');
    $kategori->save();

    return redirect()->route('kategori.index')->with('message', 'Data kategori baru telah ditambahkan');
  }

  /**
  * Display the specified resource.
  *
  * @param  \App\kategori  $kategori
  * @return \Illuminate\Http\Response
  */
  public function show(kategori $kategori)
  {
    //
  }

  /**
  * Show the form for editing the specified resource.
  *
  * @param  \App\kategori  $kategori
  * @return \Illuminate\Http\Response
  */
  public function edit($id)
  {
    $subtitle = 'Edit';
    $header = 'Edit Kategori';
    $title = 'Data Kategori';
    $user =  Auth::user()->username;

    $kategori = Kategori::find($id);

    return view('admins.kategori.edit')
    ->with(compact('title'))
    ->with(compact('subtitle'))
    ->with(compact('header'))
    ->with(compact('user'))
    ->with(compact('kategori'));
  }

  /**
  * Update the specified resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @param  \App\kategori  $kategori
  * @return \Illuminate\Http\Response
  */
  public function update(Request $request, kategori $kategori)
  {
    $kategori->nama = $request->get('nama');
    $kategori->keterangan = $request->get('keterangan');

    $kategori->save();
    return redirect()->route('kategori.index')->with('message', 'Data ' . $kategori->id . ' telah diupdate.');
  }

  /**
  * Remove the specified resource from storage.
  *
  * @param  \App\kategori  $kategori
  * @return \Illuminate\Http\Response
  */
  public function destroy(Kategori $kategori)
  {
    $kategori->delete();
    return redirect()->route('kategori.index')->with('message', 'Data ' . $kategori->id . ' telah dihapus.');
  }
}

resources/views/admins/kategori/addnew.blade.php
@extends('layouts.admin')

@section('title')
{{ $title }}
@endsection

@section('subtitle')
{{ $subtitle }}
@endsection

@section('content')


<h1><b>{{ $header }}</b></h1>
<hr>
@if(session()->has('message'))
<div class="alert alert-success">
  {{ session()->get('message') }}
</div>
@endif

<div>

  {{ Form::open(array('id' => 'form-kategori', 'route' => 'kategori.store', 'method' => 'POST')) }}

  <div class="form-group row">
  {!! Form::label('nama', 'Nama', array('class' => 'col-md-3 text-right d-none d-md-block control-label')) !!}
  <div class="col-md-5">
   {!! Form::text('nama', null, array('class' => 'form-control', 'placeholder' => 'Nama Kategori', 'required' => '')) !!}
 </div>
</div>

 <div class="form-group row">
  {!! Form::label('keterangan', 'Keterangan',array('class' => 'col-md-3 text-right d-none d-md-block control-label')) !!}
  <div class="col-md-5">
   {!! Form::textarea('keterangan', null, array('id' => 'keterangan', 'class' => 'form-control', 'placeholder' => 'Keterangan', 'required' => '')) !!}
 </div>
</div>

<div class="form-group row">
  <div class="offset-md-3 col-md-5">
    {!! Form::submit('Tambah', array('class' => 'btn btn-primary  control-label')) !!}
    {!! Form::reset('Batal', array('id' => 'reset', 'class' => 'btn btn-danger  control-label')) !!}
  </div>
</div>


{{ Form::close() }}
</div>



@endsection

resources/views/admins/kategori/edit.blade.php
@extends('layouts.admin')

@section('title')
{{ $title }}
@endsection

@section('subtitle')
{{ $subtitle }}
@endsection

@section('content')

<h1><b>{{ $header }}</b></h1>
<hr>
@if(session()->has('message'))
<div class="alert alert-success">
  {{ session()->get('message') }}
</div>
@endif
<div>

  {{ Form::model($kategori, array('id' => 'form-kategori', 'route' => array('kategori.update', $kategori->id),  'method' => 'PUT')) }}
  <input type="hidden" name="id" value="{{ $kategori->id }}" >

  <div class="form-group row">
   {!! Form::label('nama', 'Nama',array('class' => 'col-md-3 text-right d-none d-md-block control-label')) !!}
   <div class="col-md-5">
    {!! Form::text('nama', $kategori->nama, array('id' => 'nama', 'class' => 'form-control', 'placeholder' => 'Nama Kategori', 'required' => '')) !!}
  </div>
</div>

  <div class="form-group row">
    {!! Form::label('keterangan', 'Keterangan',array('class' => 'col-md-3 text-right d-none d-md-block control-label')) !!}
    <div class="col-md-5">
      {{ Form::textarea('keterangan', $kategori->keterangan,  array( 'id' =>'keterangan', 'class' => 'form-control', 'placeholder' => 'Ket Kategori', 'required' => '')) }}
    </div>
  </div>

  <div class="form-group row">
    <div class="offset-md-3 col-md-5">
      {!! Form::submit('Update', array('class' => 'btn btn-primary  control-label')) !!}
      {!! Form::reset('Batal', array('id' => 'reset', 'class' => 'btn btn-danger  control-label')) !!}
    </div>
  </div>

 </div>
{{ Form::close() }}
</div>
@endsection

resources/views/admins/kategori/index.blade.php
@extends('layouts.admin')

@section('title')
{{ $title }}
@endsection

@section('subtitle')
{{ $subtitle }}
@endsection

@section('content')


<h1><b>{{ $header }}</b></h1>
<hr>
@if(session()->has('message'))
<div class="alert alert-success">
	{{ session()->get('message') }}
</div>
@endif
<div class="tambah">
  <a href="{{ route('kategori.create') }}" class="btn btn-primary">Tambah Baru</a>
</div>
<div class="table-responsive">
	<table class="table table-bordered" id="dataTable" width="100%">
		<thead>
			<th>ID</th>
			<th>Nama</th>
			<th>Keterangan</th>
			<th width="8%">Aksi</th>
		</thead>
		<tbody>

      @foreach($kategori as $k)

			<tr>
				<td>{{ $k->id }}</td>
				<td>{{ $k->nama }}</td>
				<td>{{ str_limit($k->keterangan, 300) }}</td>
				<td><a href="{{ route('kategori.edit', $k->id) }}"><i class="fa fa-edit"></i></a>&nbsp;

  			  {!! Form::open(['method' => 'POST','route' => ['kategori.destroy', $k->id],'style'=>'display:inline']) !!}
					{{ csrf_field() }}

					@method('DELETE')
						<button class="no-btn btn" type="submit"><i class="fa fa-trash"></i></button>
					{{ Form::close() }}
				</td>

			</tr>

      @endforeach

		</tbody>
	</table>
</div>

@endsection