routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'KontenController@index');

Route::get('baca-artikel/{id}', 'KontenController@baca_artikel');

Route::get('gambar-galeri', 'KontenController@galeri');

Route::get('web-kategori/{id}', 'KontenController@kategori');

Route::get('kontak', 'KontenController@kontak');

Route::post('kontak', [
    'uses' => 'KontenController@simpan_kontak',
    'as' => 'simpan_kontak'
]);

Route::get('login', [
    'uses' => 'KontenController@login',
    'as' => 'login'
]);

Route::post('login', [
    'uses' => 'KontenController@cek_login',
    'as' => 'cek_login'
]);

Route::group(['middleware' => 'auth'], function () {

    Route::get('dashboard', [
        'uses' => 'AdminController@index',
        'as' => 'dashboard'
    ]);

    Route::get('logout', [
        'uses' => 'AdminController@logout',
        'as' => 'logout'
    ]);

    Route::get('baca-kontak/{$id}', [
        'uses' => 'AdminController@baca_kontak',
        'as' => 'baca-kontak'
    ]);

    Route::get('hapus_kontak/{id}', 'AdminController@hapus_kontak');

    Route::resource('artikel', 'ArtikelController');
    Route::resource('kategori', 'KategoriController');
    Route::resource('produk', 'ProdukController');
    Route::resource('galeri', 'GaleriController');
    Route::resource('carousel', 'CarouselController');
    Route::resource('setting', 'SettingController');
    Route::resource('mesin', 'MesinController');

    Route::get('manajemen_gambar_artikel', 'AdminController@manajemen_gambar_artikel');
    Route::post('upload_gambar_artikel', 'AdminController@upload_gambar_artikel');
    Route::get('hapus_gambar_artikel/{file}', 'AdminController@hapus_gambar_artikel');

    Route::get('manajemen_gambar_produk', 'AdminController@manajemen_gambar_produk');
    Route::post('upload_gambar_produk', 'AdminController@upload_gambar_produk');
    Route::get('hapus_gambar_produk/{file}', 'AdminController@hapus_gambar_produk');

    Route::get('manajemen_gambar_galeri', 'AdminController@manajemen_gambar_galeri');
    Route::post('upload_gambar_galeri', 'AdminController@upload_gambar_galeri');
    Route::get('hapus_gambar_galeri/{file}', 'AdminController@hapus_gambar_galeri');

    Route::get('manajemen_gambar_carousel', 'AdminController@manajemen_gambar_carousel');
    Route::post('upload_gambar_carousel', 'AdminController@upload_gambar_carousel');
    Route::get('hapus_gambar_carousel/{file}', 'AdminController@hapus_gambar_carousel');

    Route::get('manajemen_gambar_mesin', 'AdminController@manajemen_gambar_mesin');
    Route::post('upload_gambar_mesin', 'AdminController@upload_gambar_mesin');
    Route::get('hapus_gambar_mesin/{file}', 'AdminController@hapus_gambar_mesin');

});

//Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

//==============================Testing================================//

Route::get('/testing', function () {
    return view('testing');
});

Route::get('/testing2', function () {
    $files = File::allFiles(public_path('images/caraousel'));

    $caraousel = array();

    foreach ($files as $file) {
        array_push($caraousel, basename((string)$file));
    }

    return $caraousel[0];
});

Route::get('/testing3', function () {
    $carousels = App\Carousel::get();
    return $carousels[3]->gambar;
});

Route::get('/caraousel', function () {
    $caraousels = App\Caraousel::all();
    return $caraousels;
});
//=========================== End Testing =================================//

app/Galeri.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Galeri extends Model
{
    protected $table = 'galeri';

    	 public $timestamps = false;
}

app/Http/Controllers/GaleriController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Galeri;
use Auth;

class GaleriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $galeri = Galeri::all();

        $subtitle = 'Index';
        $header = 'List Galeri';
        $title = 'Data Galeri';
        $user = Auth::user()->username;

        return view('admins.galeri.index')
            ->with(compact('galeri'))
            ->with(compact('title'))
            ->with(compact('subtitle'))
            ->with(compact('header'))
            ->with(compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $subtitle = 'Input ';
        $header = 'Input Galeri';
        $title = 'Data Galeri';
        $user = Auth::user()->username;
        $arr_filename = $this->ambil_data_gambar();

        return view('admins.galeri.addnew')
            ->with(compact('title'))
            ->with(compact('subtitle'))
            ->with(compact('header'))
            ->with(compact('user'))
            ->with(compact('kategori'))
            ->with(compact('arr_filename'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $galeri = new Galeri;

        $galeri->nama = $request->input('nama');
        $galeri->path = $request->input('path');
        $galeri->keterangan = $request->input('keterangan');
        $galeri->save();

        return redirect()->route('galeri.index')->with('message', 'Data galeri baru telah ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $subtitle = 'Galeri ';
        $header = 'Edit Galeri';
        $title = 'Data Galeri';
        $user = Auth::user()->username;
        $arr_filename = $this->ambil_data_gambar();

        $galeri = Galeri::find($id);

        return view('admins.galeri.edit')
            ->with(compact('title'))
            ->with(compact('subtitle'))
            ->with(compact('header'))
            ->with(compact('user'))
            ->with(compact('galeri'))
            ->with(compact('arr_filename'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Galeri $galeri)
    {
        $galeri->nama = $request->get('nama');
        $galeri->path = $request->get('path');
        $galeri->keterangan = $request->get('keterangan');


        $galeri->save();
        return redirect()->route('galeri.index')->with('message', 'Data ' . $galeri->id . ' telah diupdate.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Galeri $galeri)
    {

        $galeri->delete();
        return redirect()->route('galeri.index')->with('message', 'Data ' . $galeri->id . ' telah dihapus.');
    }

    function ambil_data_gambar()
    {
        $files = glob(public_path('/images/galeri/*.jpg'));
        $arr_filename = array();

        for ($i = 0; $i < count($files); $i++) {
            $row['filename'] = basename($files[$i]);
            $arr_filename[$row['filename']] = $row['filename'];

        }

        $arr_filename = array(''=>'--- Pilih Gambar ---') + $arr_filename;

        //$arr_filename = array_merge(array('no-pict.jpg' => '--- Silahkan Pilih Gambar ---'), $arr_filename);

        return $arr_filename;
    }
}

resources/views/admins/galeri/addnew.blade.php
@extends('layouts.admin')

@section('title')
    {{ $title }}
@endsection

@section('subtitle')
    {{ $subtitle }}
@endsection

@section('content')


    <h1><b>{{ $header }}</b></h1>
    <hr>
    @if(session()->has('message'))
        <div class="alert alert-success">
            {{ session()->get('message') }}
        </div>
    @endif

    <div>
        {{ Form::open(array('id' => 'form-galeri', 'route' => 'galeri.store', 'method' => 'POST')) }}

        <div class="form-group row">
            {!! Form::label('nama', 'Nama', array('class' => 'col-md-3 text-right d-none d-md-block control-label')) !!}
            <div class="col-md-5">
                {!! Form::text('nama', null, array('class' => 'form-control', 'placeholder' => 'Nama Galeri', 'required' => '')) !!}
            </div>
        </div>

        <div class="form-group row">
            {!! Form::label('path', 'Path',array('class' => 'data-path col-md-3 text-right d-none d-md-block control-label')) !!}
            <div class="col-md-5">
                {{ Form::select('path', $arr_filename, null,  array('id' => 'gambar-galeri-src', 'class' => 'form-control', 'required' => '')) }}
                <img src="{{ URL::to('/') }}/images/galeri/no-pict.jpg" id="gambar-galeri" class="img-fluid" alt="Responsive image">
            </div>
            <div class="offset-md-3 col-md-5">
            </div>
        </div>

        <div class="form-group row">
            {!! Form::label('keterangan', 'Keterangan',array('class' => 'col-md-3 text-right d-none d-md-block control-label')) !!}
            <div class="col-md-5">
                {!! Form::textarea('keterangan', null, array('id' => 'keterangan', 'class' => 'form-control', 'placeholder' => 'Keterangan', 'required' => '')) !!}
            </div>
        </div>

        <div class="form-group row">
            <div class="offset-md-3 col-md-5">
                {!! Form::submit('Tambah', array('class' => 'btn btn-primary  control-label')) !!}
                {!! Form::reset('Batal', array('id' => 'reset', 'class' => 'btn btn-danger  control-label')) !!}
            </div>
        </div>


        {{ Form::close() }}
    </div>



@endsection

resources/views/admins/galeri/edit.blade.php
@extends('layouts.admin')

@section('title')
    {{ $title }}
@endsection

@section('subtitle')
    {{ $subtitle }}
@endsection

@section('content')

    <h1><b>{{ $header }}</b></h1>
    <hr>
    @if(session()->has('message'))
        <div class="alert alert-success">
            {{ session()->get('message') }}
        </div>
    @endif
    <div>

        {{ Form::model($galeri, array('id' => 'form-galeri', 'route' => array('galeri.update', $galeri->id),  'method' => 'PUT')) }}
        <input type="hidden" name="id" value="{{ $galeri->id }}" >

        <div class="form-group row">
            {!! Form::label('nama', 'Nama', array('class' => 'col-md-3 text-right d-none d-md-block control-label')) !!}
            <div class="col-md-5">
                {!! Form::text('nama', $galeri->nama, array('class' => 'form-control', 'placeholder' => 'Nama Galeri', 'required' => '')) !!}
            </div>
        </div>

        <div class="form-group row">
            {!! Form::label('path', 'Path',array('class' => 'data-path col-md-3 text-right d-none d-md-block control-label')) !!}
            <div class="col-md-5">
                {{ Form::select('path', $arr_filename, $galeri->path,  array('id' => 'gambar-galeri-src', 'class' => 'form-control', 'required' => '')) }}
                <img src="{{ URL::to('/') }}/images/galeri/{{ $galeri->path }}" id="gambar-galeri" class="img-fluid" alt="Responsive image">
            </div>
            <div class="offset-md-3 col-md-5">
            </div>
        </div>

        <div class="form-group row">
            {!! Form::label('keterangan', 'Keterangan',array('class' => 'col-md-3 text-right d-none d-md-block control-label')) !!}
            <div class="col-md-5">
                {!! Form::textarea('keterangan', $galeri->keterangan, array('id' => 'keterangan', 'class' => 'form-control', 'placeholder' => 'Keterangan', 'required' => '')) !!}
            </div>
        </div>

        <div class="form-group row">
            <div class="offset-md-3 col-md-5">
                {!! Form::submit('Update', array('class' => 'btn btn-primary  control-label')) !!}
                {!! Form::reset('Batal', array('id' => 'reset', 'class' => 'btn btn-danger  control-label')) !!}
            </div>
        </div>

        {{ Form::close() }}
    </div>
@endsection

resources/views/admins/galeri/index.blade.php
@extends('layouts.admin')

@section('title')
    {{ $title }}
@endsection

@section('subtitle')
    {{ $subtitle }}
@endsection

@section('content')


    <h1><b>{{ $header }}</b></h1>
    <hr>
    @if(session()->has('message'))
        <div class="alert alert-success">
            {{ session()->get('message') }}
        </div>
    @endif
    <div class="tambah">
        <a href="{{ route('galeri.create') }}" class="btn btn-primary">Tambah Baru</a>
    </div>
    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%">
            <thead>
            <th width="10">ID</th>
            <th width="25%">Nama</th>
            <th width="15">Path</th>
            <th width="40">Keterangan</th>
            <th width="10%">Aksi</th>
            </thead>
            <tbody>

            @foreach($galeri as $g)

                <tr>
                    <td>{{ $g->id }}</td>
                    <td>{{ $g->nama }}</td>
                    <td><img style="width:40%" src="{{ URL::to('/') }}/images/galeri/{{ $g->path }}"></td>
                    <td>{{ str_limit($g->keterangan, 300) }}</td>
                    <td><a href="{{ route('galeri.edit', $g->id) }}"><i class="fa fa-edit"></i></a>&nbsp;

                        {!! Form::open(['method' => 'POST','route' => ['galeri.destroy', $g->id],'style'=>'display:inline']) !!}
                        {{ csrf_field() }}

                        @method('DELETE')
                        <button class="no-btn btn" type="submit"><i class="fa fa-trash"></i></button>
                        {{ Form::close() }}
                    </td>
                </tr>
            @endforeach

            </tbody>
        </table>
    </div>

@endsection