routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'KontenController@index');

Route::get('baca-artikel/{id}', 'KontenController@baca_artikel');

Route::get('gambar-galeri', 'KontenController@galeri');

Route::get('web-kategori/{id}', 'KontenController@kategori');

Route::get('kontak', 'KontenController@kontak');

Route::post('kontak', [
    'uses' => 'KontenController@simpan_kontak',
    'as' => 'simpan_kontak'
]);

Route::get('login', [
    'uses' => 'KontenController@login',
    'as' => 'login'
]);

Route::post('login', [
    'uses' => 'KontenController@cek_login',
    'as' => 'cek_login'
]);

Route::group(['middleware' => 'auth'], function () {

    Route::get('dashboard', [
        'uses' => 'AdminController@index',
        'as' => 'dashboard'
    ]);

    Route::get('logout', [
        'uses' => 'AdminController@logout',
        'as' => 'logout'
    ]);

    Route::get('baca-kontak/{$id}', [
        'uses' => 'AdminController@baca_kontak',
        'as' => 'baca-kontak'
    ]);

    Route::get('hapus_kontak/{id}', 'AdminController@hapus_kontak');

    Route::resource('artikel', 'ArtikelController');
    Route::resource('kategori', 'KategoriController');
    Route::resource('produk', 'ProdukController');
    Route::resource('galeri', 'GaleriController');
    Route::resource('carousel', 'CarouselController');
    Route::resource('setting', 'SettingController');
    Route::resource('mesin', 'MesinController');

    Route::get('manajemen_gambar_artikel', 'AdminController@manajemen_gambar_artikel');
    Route::post('upload_gambar_artikel', 'AdminController@upload_gambar_artikel');
    Route::get('hapus_gambar_artikel/{file}', 'AdminController@hapus_gambar_artikel');

    Route::get('manajemen_gambar_produk', 'AdminController@manajemen_gambar_produk');
    Route::post('upload_gambar_produk', 'AdminController@upload_gambar_produk');
    Route::get('hapus_gambar_produk/{file}', 'AdminController@hapus_gambar_produk');

    Route::get('manajemen_gambar_galeri', 'AdminController@manajemen_gambar_galeri');
    Route::post('upload_gambar_galeri', 'AdminController@upload_gambar_galeri');
    Route::get('hapus_gambar_galeri/{file}', 'AdminController@hapus_gambar_galeri');

    Route::get('manajemen_gambar_carousel', 'AdminController@manajemen_gambar_carousel');
    Route::post('upload_gambar_carousel', 'AdminController@upload_gambar_carousel');
    Route::get('hapus_gambar_carousel/{file}', 'AdminController@hapus_gambar_carousel');

    Route::get('manajemen_gambar_mesin', 'AdminController@manajemen_gambar_mesin');
    Route::post('upload_gambar_mesin', 'AdminController@upload_gambar_mesin');
    Route::get('hapus_gambar_mesin/{file}', 'AdminController@hapus_gambar_mesin');

});

//Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

//==============================Testing================================//

Route::get('/testing', function () {
    return view('testing');
});

Route::get('/testing2', function () {
    $files = File::allFiles(public_path('images/caraousel'));

    $caraousel = array();

    foreach ($files as $file) {
        array_push($caraousel, basename((string)$file));
    }

    return $caraousel[0];
});

Route::get('/testing3', function () {
    $carousels = App\Carousel::get();
    return $carousels[3]->gambar;
});

Route::get('/caraousel', function () {
    $caraousels = App\Caraousel::all();
    return $caraousels;
});
//=========================== End Testing =================================//

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" type="image/png" href="{{ asset('images/favicon-96x96.png') }}">

  <title>@yield('title')</title>
  <!-- Bootstrap core CSS-->
  <link href="{{ asset('vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <!-- Custom fonts for this template-->
  <link href="{{ asset('vendor/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">
  <!-- Colorbox CSS -->
  <link href="{{ asset('vendor/colorbox/example2/colorbox.css') }}" rel="stylesheet"  />
  <!-- Dropzone -->
  {{--<link href="{{ asset('vendor/dropzone/min/basic.min.css') }}" rel="stylesheet" type="text/css">--}}
  <link href="{{ asset('vendor/dropzone/min/dropzone.min.css') }}" rel="stylesheet" type="text/css">
  <!-- Custom styles for this template-->
 <link href="{{ asset('vendor/sb-admin/css/sb-admin.min.css') }}" rel="stylesheet">
  <!-- Custom styles Mulya Jaya -->
  <link href="{{ asset('css/style.css') }}" rel="stylesheet">
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
  <a class="navbar-brand" href="{{ route('dashboard')  }}">{{ $workshop->nama_perusahaan }}</a>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">

      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
        <a class="nav-link" href="{{ route('artikel.index') }}">
          <i class="fa fa-fw fa-edit"></i>
          <span class="nav-link-text">Artikel</span>
        </a>
      </li>

      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
        <a class="nav-link" href="{{ route('kategori.index') }}">
          <i class="fa fa-fw fa-edit"></i>
          <span class="nav-link-text">Kategori</span>
        </a>
      </li>

      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
        <a class="nav-link" href="{{ route('produk.index') }}">
          <i class="fa fa-fw fa-edit"></i>
          <span class="nav-link-text">Produk</span>
        </a>
      </li>

      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
        <a class="nav-link" href="{{ route('galeri.index') }}">
          <i class="fa fa-fw fa-edit"></i>
          <span class="nav-link-text">Galeri</span>
        </a>
      </li>

      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
        <a class="nav-link" href="{{ route('carousel.index') }}">
          <i class="fa fa-fw fa-edit"></i>
          <span class="nav-link-text">Carousel</span>
        </a>
      </li>

      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
        <a class="nav-link" href="{{ route('mesin.index') }}">
          <i class="fa fa-fw fa-edit"></i>
          <span class="nav-link-text">Mesin</span>
        </a>
      </li>

      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Components">
        <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseComponents" data-parent="#exampleAccordion">
          <i class="fa fa-fw fa-upload"></i>
          <span class="nav-link-text">Manajemen File</span>
        </a>
        <ul class="sidenav-second-level collapse" id="collapseComponents">
          <li>
            <a href="{{ url('manajemen_gambar_artikel')  }}">Artikel</a>
          </li>
          <li>
            <a href="{{ url('manajemen_gambar_produk')  }}">Produk</a>
          </li>
          <li>
            <a href="{{ url('manajemen_gambar_galeri')  }}">Galeri</a>
          </li>
          <li>
            <a href="{{ url('manajemen_gambar_carousel')  }}">Carousel</a>
          </li>
          <li>
            <a href="{{ url('manajemen_gambar_mesin')  }}">Mesin</a>
          </li>
        </ul>
      </li>

      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
        <a class="nav-link" href="{{ route('setting.index') }}">
          <i class="fa fa-fw fa-gears"></i>
          <span class="nav-link-text">Setting</span>
        </a>
      </li>

    </ul>
    <ul class="navbar-nav sidenav-toggler">
      <li class="nav-item">
        <a class="nav-link text-right" id="sidenavToggler">
          <i class="fa fa-fw fa-angle-left"></i>
        </a>
      </li>
    </ul>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      <li class="nav-item">
        <a class="nav-link">Tanggal : <span id="tanggal"></span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link">Jam : <span id="waktu"></span></a>
      </li>

    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a href="{{ route('dashboard') }}" class="nav-link">Selamat Datang, {{ $user }}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
          <i class="fa fa-fw fa-sign-out"></i>Keluar</a>
      </li>
    </ul>
  </div>
</nav>
<div class="content-wrapper">
  <div class="container-fluid">
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="{{ route('dashboard') }}">@yield('title')</a>
      </li>
      <li class="breadcrumb-item active">@yield('subtitle')</li>
    </ol>
    <div class="row">
      <div class="col-12">
        @yield('content')
      </div>
    </div>
    <!-- /.container-fluid-->
    <!-- /.content-wrapper-->
    <footer class="sticky-footer">
      <div class="container">
        <div class="text-center">
          <small>Created By Philip Loa Pleyto 2018</small>
        </div>
      </div>
    </footer>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Yakin ingin keluar?</h5>
          </div>
          <div class="modal-body"><p>Pilih tombol keluar jika kamu mengakhiri session admin.</p></div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Batal</button>
            <a class="btn btn-primary" href="{{ url('logout') }}">Keluar</a>
          </div>
        </div>
      </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <!-- Core plugin JavaScript-->
    <script src="{{ asset('vendor/jquery-easing/jquery.easing.min.js') }}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{{ asset('vendor/sb-admin/js/sb-admin.min.js') }}"></script>
    <!-- Moment javascript -->
    <script src="{{ asset('vendor/moment/moment.js') }}"></script>
    <!-- Gallery Colorbox -->
    <script src="{{ asset('vendor/colorbox/jquery.colorbox-min.js')}}"></script>
    <!-- Dropzone -->
    <script src="{{ asset('vendor/dropzone/min/dropzone.min.js') }}"></script>
    <!-- Jquery Validate -->
    <script src="{{ asset('vendor/jquery-validation/dist/jquery.validate.min.js') }}"></script>
    <!-- Custom scripts for CV Mulya Jaya-->
    <script src="{{ asset('js/script-admin.js') }}"></script>
  </div>
</div>
</body>

</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/carousel.blade.php
<div id="carouselIndicators" class="carousel slide" >
  <ul class="carousel-indicators">
    @foreach ($carousels as $carousel)
      @if ($carousel->id === 1)
      <li data-target="#carouselIndicators" data-slide-to="{{ $carousel->id - 1 }}" class="active"></li>
      @else
      <li data-target="#carouselIndicators" data-slide-to="{{ $carousel->id - 1}}"></li>
      @endif
    @endforeach
  </ul>
  <div class="carousel-inner">
    @foreach ($carousels as $carousel)
      @if($carousel->id === 1)
        <div class="carousel-item active">
          <img class="d-block w-100" src="{{ url('/images/carousel/' . $carousel->gambar) }}">
          <div class="carousel-caption d-none d-md-block">
            <h5>{{ $carousel->nama }}</h5>  
          </div>
        </div>
      @else
        <div class="carousel-item">
          <img class="d-block w-100" src="{{ url('/images/carousel/' . $carousel->gambar) }}">
          <div class="carousel-caption d-none d-md-block">
            <h5>{{ $carousel->nama }}</h5>  
          </div>
        </div>
      @endif
    @endforeach
  </div>
  <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

resources/views/layouts/cover.blade.php
<div class="cover">
  <h1>{{ $workshop->nama_perusahaan }}</h1>
  <h2>{{ $workshop->tag }}</h2>
</div>

resources/views/layouts/errors.blade.php
@if (count($errors))
<div class="col-md-9">  		
  
   @foreach ($errors->all() as $error)
   <span class="error">{{  $error }}</span>
   @endforeach
 
</div>
@endif

resources/views/layouts/footer.blade.php
    <div class="footer">
    	<p class="custom-text-footer"><span class="glyphicon glyphicon-registration-mark"></span> Created By Philip Loa Pleyto 2018 </p>
    </div>

resources/views/layouts/modal.blade.php
<!-- The Modal -->
<div class="modal" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <!-- <div class="modal-header">
        <h4 class="modal-title"></h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div> -->

      <!-- Modal body -->
      <div class="modal-body">
          <img src="" class="imagepreview">
      </div>

      <!-- Modal footer -->
<!--       <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
      </div>
 -->
    </div>
  </div>
</div>

resources/views/layouts/upload.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@yield('title')</title>
    <!-- Bootstrap core CSS-->
    <link href="{{ asset('vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="{{ asset('vendor/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">
    <!-- Colorbox CSS -->
    <link href="{{ asset('vendor/colorbox/example2/colorbox.css') }}" rel="stylesheet"  />
    <!-- Dropzone -->
    {{--<link href="{{ asset('vendor/dropzone/min/basic.min.css') }}" rel="stylesheet" type="text/css">--}}
    <link href="{{ asset('vendor/dropzone/min/dropzone.min.css') }}" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template-->
    <link href="{{ asset('vendor/sb-admin/css/sb-admin.min.css') }}" rel="stylesheet">
    <!-- Custom styles Mulya Jaya -->
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="{{ route('dashboard')  }}">CV. Mulya Jaya</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">

            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
                <a class="nav-link" href="{{ route('artikel.index') }}">
                    <i class="fa fa-fw fa-edit"></i>
                    <span class="nav-link-text">Artikel</span>
                </a>
            </li>

            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
                <a class="nav-link" href="{{ route('kategori.index') }}">
                    <i class="fa fa-fw fa-edit"></i>
                    <span class="nav-link-text">Kategori</span>
                </a>
            </li>

            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
                <a class="nav-link" href="{{ route('produk.index') }}">
                    <i class="fa fa-fw fa-edit"></i>
                    <span class="nav-link-text">Produk</span>
                </a>
            </li>

            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
                <a class="nav-link" href="{{ route('galeri.index') }}">
                    <i class="fa fa-fw fa-edit"></i>
                    <span class="nav-link-text">Galeri</span>
                </a>
            </li>

            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
                <a class="nav-link" href="{{ route('carousel.index') }}">
                    <i class="fa fa-fw fa-edit"></i>
                    <span class="nav-link-text">Carousel</span>
                </a>
            </li>

            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
                <a class="nav-link" href="{{ route('mesin.index') }}">
                    <i class="fa fa-fw fa-edit"></i>
                    <span class="nav-link-text">Mesin</span>
                </a>
            </li>

            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Components">
                <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseComponents" data-parent="#exampleAccordion">
                    <i class="fa fa-fw fa-upload"></i>
                    <span class="nav-link-text">Upload Gambar</span>
                </a>
                <ul class="sidenav-second-level collapse" id="collapseComponents">
                    <li>
                        <a href="{{ url('manajemen_gambar_artikel')  }}">Artikel</a>
                    </li>
                    <li>
                        <a href="{{ url('manajemen_gambar_produk')  }}">Produk</a>
                    </li>
                    <li>
                        <a href="{{ url('manajemen_gambar_galeri')  }}">Galeri</a>
                    </li>
                    <li>
                        <a href="{{ url('manajemen_gambar_carousel')  }}">Carousel</a>
                    </li>
                    <li>
                        <a href="{{ url('manajemen_gambar_mesin')  }}">Mesin</a>
                    </li>
                </ul>
            </li>

            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
                <a class="nav-link" href="{{ route('setting.edit', '1') }}">
                    <i class="fa fa-fw fa-gears"></i>
                    <span class="nav-link-text">Setting</span>
                </a>
            </li>

        </ul>
        <ul class="navbar-nav sidenav-toggler">
            <li class="nav-item">
                <a class="nav-link text-right" id="sidenavToggler">
                    <i class="fa fa-fw fa-angle-left"></i>
                </a>
            </li>
        </ul>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
            <li class="nav-item">
                <a class="nav-link">Tanggal : <span id="tanggal"></span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link">Jam : <span id="waktu"></span></a>
            </li>

        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a href="{{ route('dashboard') }}" class="nav-link">Selamat Datang, {{ $user }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
                    <i class="fa fa-fw fa-sign-out"></i>Keluar</a>
            </li>
        </ul>
    </div>
</nav>
<div class="content-wrapper">
    <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('dashboard') }}">@yield('title')</a>
            </li>
            <li class="breadcrumb-item active">@yield('subtitle')</li>
        </ol>
        <div class="row">

                @yield('content')

        </div>
        <!-- /.container-fluid-->
        <!-- /.content-wrapper-->
        <footer class="sticky-footer">
            <div class="container">
                <div class="text-center">
                    <small>Created By Philip Loa Pleyto 2018</small>
                </div>
            </div>
        </footer>
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fa fa-angle-up"></i>
        </a>
        <!-- Logout Modal-->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Yakin ingin keluar?</h5>
                    </div>
                    <div class="modal-body"><p>Pilih tombol keluar jika ingin mengakhiri session admin.</p></div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Batal</button>
                        <a class="btn btn-primary" href="{{ url('logout') }}">Keluar</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Bootstrap core JavaScript-->
        <script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
        <script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
        <!-- Core plugin JavaScript-->
        <script src="{{ asset('vendor/jquery-easing/jquery.easing.min.js') }}"></script>
        <!-- Custom scripts for all pages-->
        <script src="{{ asset('vendor/sb-admin/js/sb-admin.min.js') }}"></script>
        <!-- Moment javascript -->
        <script src="{{ asset('vendor/moment/moment.js') }}"></script>
        <!-- Gallery Colorbox -->
        <script src="{{ asset('vendor/colorbox/jquery.colorbox-min.js')}}"></script>
        <!-- Dropzone -->
        <script src="{{ asset('vendor/dropzone/min/dropzone.min.js') }}"></script>
        <!-- Jquery Validate -->
        <script src="{{ asset('vendor/jquery-validation/dist/jquery.validate.min.js') }}"></script>
        <!-- Custom scripts for CV Mulya Jaya-->
        <script src="{{ asset('js/script-admin.js') }}"></script>
    </div>
</div>
</body>

</html>